// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo-1k9D4r9siXuprQFrW0eKtROKpLJCKE',
    appId: '1:550873151113:web:276492042bf60c671b7858',
    messagingSenderId: '550873151113',
    projectId: 'stalker-bb55d',
    authDomain: 'stalker-bb55d.firebaseapp.com',
    storageBucket: 'stalker-bb55d.appspot.com',
    measurementId: 'G-YMTS0ZER3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAThue00Nf0N-V76jmeFIAWafcKaHSrTaY',
    appId: '1:550873151113:android:609bf14ef3c5a1681b7858',
    messagingSenderId: '550873151113',
    projectId: 'stalker-bb55d',
    storageBucket: 'stalker-bb55d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbphJ1tFeeyo6718xV2sQ8G1Ye9PRkpLU',
    appId: '1:550873151113:ios:d3a63ab9066751f81b7858',
    messagingSenderId: '550873151113',
    projectId: 'stalker-bb55d',
    storageBucket: 'stalker-bb55d.appspot.com',
    iosClientId: '550873151113-s5mv2o7l7020dhmgvjpmdn5rvkdg8b77.apps.googleusercontent.com',
    iosBundleId: 'com.example.stalker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbphJ1tFeeyo6718xV2sQ8G1Ye9PRkpLU',
    appId: '1:550873151113:ios:d3a63ab9066751f81b7858',
    messagingSenderId: '550873151113',
    projectId: 'stalker-bb55d',
    storageBucket: 'stalker-bb55d.appspot.com',
    iosClientId: '550873151113-s5mv2o7l7020dhmgvjpmdn5rvkdg8b77.apps.googleusercontent.com',
    iosBundleId: 'com.example.stalker',
  );
}
